<?php
/* Copyright (C) 2007-2017  Laurent Destailleur     <eldy@users.sourceforge.net>
 * Copyright (C) 2024       Frédéric France         <frederic.france@free.fr>
 * Copyright (C) 2025		Grégory Maza             <gregory.maza@atm-consulting.fr>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

/**
 *   	\file       chaumeilrfa_list_fourn.php
 *		\ingroup    clichaumeil
 *		\brief      List page for chaumeilrfa_fourn
 */



// Load Dolibarr environment
$res = 0;
// Try main.inc.php into web root known defined into CONTEXT_DOCUMENT_ROOT (not always defined)
if (!$res && !empty($_SERVER["CONTEXT_DOCUMENT_ROOT"])) {
	$res = @include $_SERVER["CONTEXT_DOCUMENT_ROOT"]."/main.inc.php";
}
// Try main.inc.php into web root detected using web root calculated from SCRIPT_FILENAME
$tmp = empty($_SERVER['SCRIPT_FILENAME']) ? '' : $_SERVER['SCRIPT_FILENAME'];
$tmp2 = realpath(__FILE__);
$i = strlen($tmp) - 1;
$j = strlen($tmp2) - 1;
while ($i > 0 && $j > 0 && isset($tmp[$i]) && isset($tmp2[$j]) && $tmp[$i] == $tmp2[$j]) {
	$i--;
	$j--;
}
if (!$res && $i > 0 && file_exists(substr($tmp, 0, ($i + 1))."/main.inc.php")) {
	$res = @include substr($tmp, 0, ($i + 1))."/main.inc.php";
}
if (!$res && $i > 0 && file_exists(dirname(substr($tmp, 0, ($i + 1)))."/main.inc.php")) {
	$res = @include dirname(substr($tmp, 0, ($i + 1)))."/main.inc.php";
}
// Try main.inc.php using relative path
if (!$res && file_exists("../main.inc.php")) {
	$res = @include "../main.inc.php";
}
if (!$res && file_exists("../../main.inc.php")) {
	$res = @include "../../main.inc.php";
}
if (!$res && file_exists("../../../main.inc.php")) {
	$res = @include "../../../main.inc.php";
}
if (!$res) {
	die("Include of main fails");
}

require_once DOL_DOCUMENT_ROOT.'/core/class/html.formcompany.class.php';
require_once DOL_DOCUMENT_ROOT.'/core/class/html.formother.class.php';
require_once DOL_DOCUMENT_ROOT.'/compta/facture/class/facture.class.php';
require_once DOL_DOCUMENT_ROOT.'/fourn/class/fournisseur.facture.class.php';
require_once DOL_DOCUMENT_ROOT.'/core/lib/date.lib.php';
require_once DOL_DOCUMENT_ROOT.'/core/lib/company.lib.php';
require_once DOL_DOCUMENT_ROOT.'/core/lib/functions.lib.php';
// load module libraries
require_once __DIR__.'/class/chaumeilrfa.class.php';
// for other modules
//dol_include_once('/othermodule/class/otherobject.class.php');

/**
 * @var Conf $conf
 * @var DoliDB $db
 * @var HookManager $hookmanager
 * @var Translate $langs
 * @var User $user
 */

// Load translation files required by the page
$langs->loadLangs(array("clichaumeil@clichaumeil", "other"));

// Get parameters
$action     = GETPOST('action', 'aZ09') ? GETPOST('action', 'aZ09') : 'view'; // The action 'create'/'add', 'edit'/'update', 'view', ...
$show_files = GETPOSTINT('show_files'); // Show files area generated by bulk actions ?
$confirm    = GETPOST('confirm', 'alpha'); // Result of a confirmation
$cancel     = GETPOST('cancel', 'alpha'); // We click on a Cancel button
$toselect   = GETPOST('toselect', 'array:int'); // Array of ids of elements selected into a list
$contextpage = GETPOST('contextpage', 'aZ') ? GETPOST('contextpage', 'aZ') : str_replace('_', '', basename(dirname(__FILE__)).basename(__FILE__, '.php')); // To manage different context of search
$backtopage = GETPOST('backtopage', 'alpha'); // Go back to a dedicated page
$optioncss  = GETPOST('optioncss', 'aZ'); // Option for the css output (always '' except when 'print')
$mode       = GETPOST('mode', 'aZ'); // The display mode ('list', 'kanban', 'hierarchy', 'calendar', 'gantt', ...)
$groupby = GETPOST('groupby', 'aZ09');	// Example: $groupby = 'p.fk_opp_status' or $groupby = 'p.fk_statut'

$id = GETPOSTINT('id');
$ref = GETPOST('ref', 'alpha');
$socid = GETPOSTINT('socid');
$search_year = GETPOST('yearid', 'int');
if (empty($search_year)){
	$search_year = date('Y');
}


// Load variable for pagination
$limit = GETPOSTINT('limit') ? GETPOSTINT('limit') : $conf->liste_limit;
$sortfield = GETPOST('sortfield', 'aZ09comma');
$sortorder = GETPOST('sortorder', 'aZ09comma');
$page = GETPOSTISSET('pageplusone') ? (GETPOSTINT('pageplusone') - 1) : GETPOSTINT('page');
if (empty($page) || $page < 0 || GETPOST('button_search', 'alpha') || GETPOST('button_removefilter', 'alpha')) {
	// If $page is not defined, or '' or -1 or if we click on clear filters
	$page = 0;
}
$offset = $limit * $page;
$pageprev = $page - 1;
$pagenext = $page + 1;

// Initialize technical objects
$object = new ChaumeilRfa($db);
$object->fields = $arrayfields = array(
	'fk_soc' => array(
		'label'   => 'Fournisseur',
		'checked' => 1,
		'type' => 'integer:Societe:societe/class/societe.class.php:1',
		'enabled' => 1,
		'visible' => 1,
		'position'=> 10
	),
	'ca_achats' => array(
		'label'   => 'CA achats année HT',
		'checked' => 1,
		'type' => 'price',
		'enabled' => 1,
		'visible' => 1,
		'position'=> 20,
		'help'    => 'Montant HT achats sur l’année en cours'
	),
	'taux_rfa' => array(
		'label' => 'Taux %',
		'checked' => 1,
		'type' => 'float',
		'enabled' => 1,
		'visible' => 1,
		'position' => 20,
		'help' => 'Taux du palier atteint'
	),
	'discount_amount_rfa' => array(
		'label'   => 'Remise',
		'checked' => 1,
		'type' => 'price',
		'enabled' => 1,
		'visible' => 1,
		'position'=> 20,
		'search'=> 0,
		'help'    => 'Montant estimé de la remise à percevoir'
	),
//	'datestart' => array(
//		'label'   => 'Date début',
//		'checked' => 1,
//		'type' => 'timestamp',
//		'enabled' => 1,
//		'visible' => 0,
//		'position'=> 20,
//		'search'=> 0,
//		'help'    => 'Date de début de la RFA'
//	),
	'status' => array(
		'label'   => 'État',
		'checked' => 1,
		'type' => 'status',
		'enabled' => 1,
		'visible' => 1,
		'position'=> 20,
		'arrayofkeyval' => array("0" =>$langs->trans("RfaStatusDraft") , "1" =>$langs->trans("RfaStatusWon") , "9" =>$langs->trans("RfaStatusLost")),
		'help'    => 'État de la RFA'
	)
);
$extrafields = new ExtraFields($db);
$hookmanager->initHooks(array($contextpage,'globalrfalist')); 	// Note that conf->hooks_modules contains array of activated contexes

// Fetch optionals attributes and labels
$extrafields->fetch_name_optionals_label($object->table_element);

$search_array_options = $extrafields->getOptionalsFromPost($object->table_element, '', 'search_');

// Default sort order (if not yet defined by previous GETPOST)
if (!$sortfield) {
	reset($arrayfields);					// Reset is required to avoid key() to return null.
	$sortfield = 'fk_soc'; // Set here default search field. By default 1st field in definition.
}
if (!$sortorder) {
	$sortorder = "ASC";
}

// Initialize array of search criteria
$search_all = trim(GETPOST('search_all', 'alphanohtml'));
$search = array();
foreach ($arrayfields as $key => $val) {
	if (GETPOST('search_'.$key, 'alpha') !== '') {
		$search[$key] = GETPOST('search_'.$key, 'alpha');
	}
	if (preg_match('/^(date|timestamp|datetime)/', $val['type'])) {
		$search[$key.'_dtstart'] = dol_mktime(0, 0, 0, GETPOSTINT('search_'.$key.'_dtstartmonth'), GETPOSTINT('search_'.$key.'_dtstartday'), GETPOSTINT('search_'.$key.'_dtstartyear'));
		$search[$key.'_dtend'] = dol_mktime(23, 59, 59, GETPOSTINT('search_'.$key.'_dtendmonth'), GETPOSTINT('search_'.$key.'_dtendday'), GETPOSTINT('search_'.$key.'_dtendyear'));
	}
}

$fieldstosearchall = array();

// Definition of array of fields for columns
$tableprefix = 't';

// Extra fields
include DOL_DOCUMENT_ROOT.'/core/tpl/extrafields_list_array_fields.tpl.php';

$arrayfields = dol_sort_array($arrayfields, 'position');

// There is several ways to check permission.
// Set $enablepermissioncheck to 1 to enable a minimum low level of checks
$enablepermissioncheck = getDolGlobalInt('CLICHAUMEIL_ENABLE_PERMISSION_CHECK');
$enablepermissioncheck = 1;
if ($enablepermissioncheck) {
	$permissiontoread = $user->hasRight('clichaumeil', 'chaumeilrfa', 'read');
	$permissiontoadd = $user->hasRight('clichaumeil', 'chaumeilrfa', 'write');
	$permissiontodelete = $user->hasRight('clichaumeil', 'chaumeilrfa', 'delete');
} else {
	$permissiontoread = 1;
	$permissiontoadd = 1;
	$permissiontodelete = 1;
}

// Security check (enable the most restrictive one)
if ($user->socid > 0) {
	accessforbidden();
}
//if ($user->socid > 0) accessforbidden();
//$socid = 0; if ($user->socid > 0) $socid = $user->socid;
//$isdraft = (($object->status == $object::STATUS_DRAFT) ? 1 : 0);
//restrictedArea($user, $object->module, 0, $object->table_element, $object->element, 'fk_soc', 'rowid', $isdraft);
if (!isModEnabled("clichaumeil")) {
	accessforbidden('Module clichaumeil not enabled');
}
if (!$permissiontoread) {
	accessforbidden();
}


/*
 * Actions
 */

if (GETPOST('cancel', 'alpha')) {
	$action = 'list';
}

$parameters = array('arrayfields' => &$arrayfields);
$reshook = $hookmanager->executeHooks('doActions', $parameters, $object, $action); // Note that $action and $object may have been modified by some hooks
if ($reshook < 0) {
	setEventMessages($hookmanager->error, $hookmanager->errors, 'errors');
}

if (empty($reshook)) {
	// Selection of new fields
	include DOL_DOCUMENT_ROOT.'/core/actions_changeselectedfields.inc.php';

	// Purge search criteria
	if (GETPOST('button_removefilter_x', 'alpha') || GETPOST('button_removefilter.x', 'alpha') || GETPOST('button_removefilter', 'alpha')) { // All tests are required to be compatible with all browsers
		foreach ($arrayfields as $key => $val) {
			$search[$key] = '';
			if (preg_match('/^(date|timestamp|datetime)/', $val['type'])) {
				$search[$key.'_dtstart'] = '';
				$search[$key.'_dtend'] = '';
			}
		}
		$search_all = '';
		$toselect = array();
		$search_array_options = array();
	}

}



/*
 * View
 */

$form = new Form($db);
$formother = new FormOther($db);

$now = dol_now();

$title = $langs->trans("ChaumeilRfas");
//$help_url = "EN:Module_ChaumeilRfa|FR:Module_ChaumeilRfa_FR|ES:Módulo_ChaumeilRfa";
$help_url = '';
$morejs = array();
$morecss = array();


// Build and execute select
// --------------------------------------------------------------------
$year = date('Y');

// -- Main SELECT --
// Selects the necessary fields: supplier ID, their calculated turnover, the applicable discount rate,
// and details about the discount tier. COALESCE is used to default NULL results to 0.
$sqlRfaFourn  = "SELECT s.rowid AS fk_soc,";
$sqlRfaFourn .= "       COALESCE(ffsum.ca_achats, 0) AS ca_achats,";
$sqlRfaFourn .= "       COALESCE(rfr.raterfa, 0) AS taux_rfa,";
$sqlRfaFourn .= "       rfr.status,";
$sqlRfaFourn .= "       rfr.datestart";
$sqlRfaFourn .= "  FROM ".$db->prefix()."societe AS s"; // The base table is the list of companies.

// -- Subquery to Calculate Purchase Turnover (ffsum) --
// This LEFT JOIN calculates the total purchase turnover for each supplier.
// It sums the total_ht of all closed supplier invoices within the selected year.
$sqlRfaFourn .= "  LEFT JOIN (";
$sqlRfaFourn .= "     SELECT fk_soc, SUM(total_ht) AS ca_achats";
$sqlRfaFourn .= "       FROM ".$db->prefix()."facture_fourn";
$sqlRfaFourn .= "      WHERE fk_statut = ".FactureFournisseur::STATUS_CLOSED;
$sqlRfaFourn .= "        AND YEAR(datef) = ".$search_year;
$sqlRfaFourn .= "      GROUP BY fk_soc";
$sqlRfaFourn .= "  ) AS ffsum ON ffsum.fk_soc = s.rowid";

// -- Correlated Subquery to Find the Correct Discount Tier (rfr) --
// This LEFT JOIN finds the single, most relevant discount tier for each supplier based on their turnover.
// It joins on the rowid returned by a correlated subquery.
$sqlRfaFourn .= "  LEFT JOIN ".$db->prefix()."clichaumeil_chaumeilrfa AS rfr ON rfr.rowid = (";
$sqlRfaFourn .= "     SELECT r.rowid";
$sqlRfaFourn .= "       FROM ".$db->prefix()."clichaumeil_chaumeilrfa AS r";
$sqlRfaFourn .= "      WHERE r.fk_soc = s.rowid"; // Correlates the subquery with the main supplier.
$sqlRfaFourn .= "        AND ".$search_year." BETWEEN YEAR(r.datestart) AND YEAR(r.dateend)"; // Filters for tiers valid in the selected year.
$sqlRfaFourn .= "        AND r.palier <= ffsum.ca_achats"; // The key condition: only selects tiers the supplier has actually reached.
$sqlRfaFourn .= "      ORDER BY r.palier DESC"; // Orders the reached tiers from highest to lowest...
$sqlRfaFourn .= "      LIMIT 1"; // ...and picks only the top one (the highest achieved tier).
$sqlRfaFourn .= "  )";

// -- Main Filters --
// Filters the final result set.
$sqlRfaFourn .= " WHERE s.fournisseur = 1"; // Ensures we only select companies that are suppliers.

// The EXISTS clause filters out suppliers who do not have any discount tiers defined for the selected year.
// This is a business rule to ensure the list is relevant.
$sqlRfaFourn .= "   AND EXISTS (";
$sqlRfaFourn .= "       SELECT 1 FROM ".$db->prefix()."clichaumeil_chaumeilrfa AS r_exists";
$sqlRfaFourn .= "       WHERE r_exists.fk_soc = s.rowid";
$sqlRfaFourn .= "         AND ".$search_year." BETWEEN YEAR(r_exists.datestart) AND YEAR(r_exists.dateend)";
$sqlRfaFourn .= "   )";

// This final condition ensures that only suppliers with a positive purchase turnover are displayed.
$sqlRfaFourn .= "   AND COALESCE(ffsum.ca_achats, 0) > 0";


$sqlwhere = ''; // <= conditions dynamiques

//RECHERCHE GLOBAL - PAS LE TRI
foreach ($search as $key => $val) {
	if (array_key_exists($key, $arrayfields)) {
		//var_dump('RECHERCHE GLOBAL - PAS LE TRI');exit;
		//if ($key == 'status' && $search[$key] == -1) continue;

		$mode_search = (($object->isInt($arrayfields[$key]) || $object->isFloat($arrayfields[$key])) ? 1 : 0);

		if ($key == 'taux_rfa' && $search[$key] != '') {
			$sqlwhere .= " AND COALESCE(rfr.raterfa, 0) LIKE '%".$db->escape($search[$key])."%'";
			continue; // On saute le reste pour ce champ
		}

		if ((strpos($arrayfields[$key]['type'], 'integer:') === 0)
			|| (strpos($arrayfields[$key]['type'], 'sellist:') === 0)
			|| !empty($arrayfields[$key]['arrayofkeyval'])) {
			if ($search[$key] == '-1'
				|| ($search[$key] === '0' && (empty($arrayfields[$key]['arrayofkeyval'])
						|| !array_key_exists('0', $arrayfields[$key]['arrayofkeyval'])))) {
				$search[$key] = '';
			}
			$mode_search = 2;
		}

		if (empty($arrayfields[$key]['searchmulti'])) {
			if (!is_array($search[$key]) && $search[$key] != '') {
				if ($key == 'fk_soc') {
					$sqlwhere .= " AND s.rowid IN (" . $db->escape($search[$key]) . ")";
				} elseif ($key == 'status') {
					$sqlwhere .= " AND rfr.status = " . intval($search[$key]);
				} else {
					$sqlwhere .= " AND rfr.status = " . intval($val);
				}
			}
		} else {
			if (is_array($search[$key]) && !empty($search[$key])) {
				if ($key == 'fk_soc') {
					$sqlwhere .= " AND s.rowid IN (" . $db->sanitize(implode(',', $search[$key])) . ")";
				} elseif ($key == 'status') {
					$sqlwhere .= natural_search("rfr.status", implode(',', $search[$key]), 2); // <-- alias ici
				} else {
					$sqlwhere .= natural_search($db->escape($key), implode(',', $search[$key]), $mode_search);
				}
			}
		}

	} else {
		if (preg_match('/(_dtstart|_dtend)$/', $key) && $search[$key] != '') {
			$columnName = preg_replace('/(_dtstart|_dtend)$/', '', $key);
			if (preg_match('/^(date|timestamp|datetime)/', $arrayfields[$columnName]['type'])) {
				if (preg_match('/_dtstart$/', $key)) {
					$sqlwhere .= " AND ".$db->sanitize($columnName)." >= '".$db->idate($search[$key])."'";
				}
				if (preg_match('/_dtend$/', $key)) {
					$sqlwhere .= " AND ".$db->sanitize($columnName)." <= '".$db->idate($search[$key])."'";
				}
			}
		}
	}
}
if (!empty($search_year)) {
	$sqlwhere .= " AND YEAR(rfr.datestart) = ".((int) $search_year);
}

if ($search_all) {
	$sqlwhere .= natural_search(array_keys($fieldstosearchall), $search_all);
}

// ORDER BY séparé
$sqlorder = " ORDER BY s.nom ASC";


$sql = "SELECT";
$sql .= " ".$object->getFieldList('t');

// Add fields from extrafields
if (!empty($extrafields->attributes[$object->table_element]['label'])) {
	foreach ($extrafields->attributes[$object->table_element]['label'] as $key => $val) {
		$sql .= ($extrafields->attributes[$object->table_element]['type'][$key] != 'separate' ? ", ef.".$key." as options_".$key : "");
	}
}
// Add fields from hooks
$parameters = array();
$reshook = $hookmanager->executeHooks('printFieldListSelect', $parameters, $object, $action); // Note that $action and $object may have been modified by hook
$sql .= $hookmanager->resPrint;
$sql = preg_replace('/,\s*$/', '', $sql);

$sqlfields = $sql; // $sql fields to remove for count total

$sql .= " FROM ".$db->prefix().$object->table_element." as t";
if (isset($extrafields->attributes[$object->table_element]['label']) && is_array($extrafields->attributes[$object->table_element]['label']) && count($extrafields->attributes[$object->table_element]['label'])) {
	$sql .= " LEFT JOIN ".$db->prefix().$object->table_element."_extrafields as ef on (t.rowid = ef.fk_object)";
}
// Add table from hooks
$parameters = array();
$reshook = $hookmanager->executeHooks('printFieldListFrom', $parameters, $object, $action); // Note that $action and $object may have been modified by hook
$sql .= $hookmanager->resPrint;
if ($object->ismultientitymanaged == 1) {
	$sql .= " WHERE t.entity IN (".getEntity($object->element, (GETPOSTINT('search_current_entity') ? 0 : 1)).")";
} else {
	$sql .= " WHERE 1 = 1";
}
//SEARCH
foreach ($search as $key => $val) {

	if (array_key_exists($key, $arrayfields)) {
		$mode_search = (($object->isInt($arrayfields[$key]) || $object->isFloat($arrayfields[$key])) ? 1 : 0);
		if ($key == 'taux_rfa' && $search[$key] != '') {
			$sqlRfaFourn .= natural_search('rfr.raterfa', $search[$key], 1);
			continue;
		}

		if ((strpos($arrayfields[$key]['type'], 'integer:') === 0) || (strpos($arrayfields[$key]['type'], 'sellist:') === 0) || !empty($arrayfields[$key]['arrayofkeyval'])) {
			if ($search[$key] == '-1' || ($search[$key] === '0' && (empty($arrayfields[$key]['arrayofkeyval']) || !array_key_exists('0', $arrayfields[$key]['arrayofkeyval'])))) {
				$search[$key] = '';
			}
			$mode_search = 2;
		}
		if (empty($arrayfields[$key]['searchmulti'])) {
			if (!is_array($search[$key]) && $search[$key] != '') {
				if ($key == 'fk_soc') {
					$sqlRfaFourn .= " AND s.rowid IN (" . $db->escape($search[$key]) . ")";
				} else {
					$sqlRfaFourn .= " AND rfr.status = " . intval($search[$key]);
				}
			}
		} else {
			if (is_array($search[$key]) && !empty($search[$key])) {
				$sql .= natural_search("t.".$db->escape($key), implode(',', $search[$key]), (($key == 'status') ? 2 : $mode_search));
			}
		}
	} else {
		if (preg_match('/(_dtstart|_dtend)$/', $key) && $search[$key] != '') {
			$columnName = preg_replace('/(_dtstart|_dtend)$/', '', $key);
			if (preg_match('/^(date|timestamp|datetime)/', $arrayfields[$columnName]['type'])) {
				if (preg_match('/_dtstart$/', $key)) {
					$sql .= " AND t.".$db->sanitize($columnName)." >= '".$db->idate($search[$key])."'";
				}
				if (preg_match('/_dtend$/', $key)) {
					$sql .= " AND t.".$db->sanitize($columnName)." <= '".$db->idate($search[$key])."'";
				}
			}
		}
	}
}

if ($search_all) {
	$sql .= natural_search(array_keys($fieldstosearchall), $search_all);
}

// Add where from extra fields
include DOL_DOCUMENT_ROOT.'/core/tpl/extrafields_list_search_sql.tpl.php';
// Add where from hooks
$parameters = array();
$reshook = $hookmanager->executeHooks('printFieldListWhere', $parameters, $object, $action); // Note that $action and $object may have been modified by hook
$sql .= $hookmanager->resPrint;



$nbtotalofrecords = '';

if (!empty($socid)){
	$sql .= " AND t.fk_soc = ".$socid;
}

// Complete request and execute it with limit
$sqlRfaFourn .= $db->order($sortfield, $sortorder);
if ($limit) {
	$sqlRfaFourn .= $db->plimit($limit + 1, $offset);
}

$resql = $db->query($sqlRfaFourn);
if (!$resql) {
	dol_print_error($sqlRfaFourn);
	exit;
}
$num = $db->num_rows($resql);

// Direct jump if only one record found
if ($num == 1 && getDolGlobalInt('MAIN_SEARCH_DIRECT_OPEN_IF_ONLY_ONE') && $search_all && !$page) {
	$obj = $db->fetch_object($resql);
	$id = $obj->rowid;
	header("Location: ".dol_buildpath('/clichaumeil/chaumeilrfa_card.php', 1).'?id='.((int) $id));
	exit;
}

// Output page
// --------------------------------------------------------------------

llxHeader('', $title, $help_url, '', 0, 0, $morejs, $morecss, '', 'mod-clichaumeil page-list bodyforlist');	// Can use also classforhorizontalscrolloftabs instead of bodyforlist for a horizontal scroll in the table instead of page


$arrayofselected = is_array($toselect) ? $toselect : array();

$param = '';
if (!empty($mode)) {
	$param .= '&mode='.urlencode($mode);
}
if (!empty($contextpage) && $contextpage != $_SERVER["PHP_SELF"]) {
	$param .= '&contextpage='.urlencode($contextpage);
}
if ($limit > 0 && $limit != $conf->liste_limit) {
	$param .= '&limit='.((int) $limit);
}
if ($optioncss != '') {
	$param .= '&optioncss='.urlencode($optioncss);
}
if ($groupby != '') {
	$param .= '&groupby='.urlencode($groupby);
}
foreach ($search as $key => $val) {
	if (is_array($search[$key])) {
		foreach ($search[$key] as $skey) {
			if ($skey != '') {
				$param .= '&search_'.$key.'[]='.urlencode($skey);
			}
		}
	} elseif (preg_match('/(_dtstart|_dtend)$/', $key) && !empty($val)) {
		$param .= '&search_'.$key.'month='.GETPOSTINT('search_'.$key.'month');
		$param .= '&search_'.$key.'day='.GETPOSTINT('search_'.$key.'day');
		$param .= '&search_'.$key.'year='.GETPOSTINT('search_'.$key.'year');
	} elseif ($search[$key] != '') {
		$param .= '&search_'.$key.'='.urlencode($search[$key]);
	}
}
$param .= '&socid='.$socid;
$param .= '&yearid='.$search_year;

// Add $param from extra fields
include DOL_DOCUMENT_ROOT.'/core/tpl/extrafields_list_search_param.tpl.php';
// Add $param from hooks
$parameters = array('param' => &$param);
$reshook = $hookmanager->executeHooks('printFieldListSearchParam', $parameters, $object, $action); // Note that $action and $object may have been modified by hook
$param .= $hookmanager->resPrint;


print '<form method="POST" id="searchFormList" action="'.$_SERVER["PHP_SELF"].'">'."\n";
if ($optioncss != '') {
	print '<input type="hidden" name="optioncss" value="'.$optioncss.'">';
}
print '<input type="hidden" name="token" value="'.newToken().'">';
print '<input type="hidden" name="formfilteraction" id="formfilteraction" value="list">';
print '<input type="hidden" name="action" value="list">';
print '<input type="hidden" name="sortfield" value="'.$sortfield.'">';
print '<input type="hidden" name="sortorder" value="'.$sortorder.'">';
print '<input type="hidden" name="page" value="'.$page.'">';
print '<input type="hidden" name="contextpage" value="'.$contextpage.'">';
print '<input type="hidden" name="page_y" value="">';
print '<input type="hidden" name="mode" value="'.$mode.'">';
print '<input type="hidden" name="socid" value="'.$socid.'">';


$newcardbutton = '';
$newcardbutton .= dolGetButtonTitle($langs->trans('ViewList'), '', 'fa fa-bars imgforviewmode', $_SERVER["PHP_SELF"].'?mode=common'.preg_replace('/(&|\?)*mode=[^&]+/', '', $param), '', ((empty($mode) || $mode == 'common') ? 2 : 1), array('morecss' => 'reposition'));
$newcardbutton .= dolGetButtonTitleSeparator();

print_barre_liste($title, $page, $_SERVER["PHP_SELF"], $param, $sortfield, $sortorder, '', $num, $nbtotalofrecords, $object->picto, 0, $newcardbutton, '', $limit, 0, 0, 1);


if ($search_all) {
	$setupstring = '';
	// @phan-suppress-next-line PhanEmptyForeach
	foreach ($fieldstosearchall as $key => $val) {
		$fieldstosearchall[$key] = $langs->trans($val);
		$setupstring .= $key."=".$val.";";
	}
	print '<!-- Search done like if CHAUMEILRFA_QUICKSEARCH_ON_FIELDS = '.$setupstring.' -->'."\n";
	print '<div class="divsearchfieldfilter">'.$langs->trans("FilterOnInto", $search_all).implode(', ', $fieldstosearchall).'</div>'."\n";
}

$moreforfilter = '';

$moreforfilter = '<div class="divsearchfield">'.$moreforfilter.'</div>';

//Search Year
$moreforfilter .= $langs->trans('ByYear') ." : ". $formother->selectyear($search_year);

$parameters = array();
$reshook = $hookmanager->executeHooks('printFieldPreListTitle', $parameters, $object, $action); // Note that $action and $object may have been modified by hook
if (empty($reshook)) {
	$moreforfilter .= $hookmanager->resPrint;
} else {
	$moreforfilter = $hookmanager->resPrint;
}
$parameters = array(
	'arrayfields' => &$arrayfields,
);

if (!empty($moreforfilter)) {
	print '<div class="liste_titre liste_titre_bydiv centpercent">';
	print $moreforfilter;
	print '</div>';
}

$varpage = empty($contextpage) ? $_SERVER["PHP_SELF"] : $contextpage;
$htmlofselectarray = $form->multiSelectArrayWithCheckbox('selectedfields', $arrayfields, $varpage, $conf->main_checkbox_left_column);  // This also change content of $arrayfields with user setup
$selectedfields = ($mode != 'kanban' ? $htmlofselectarray : '');

print '<div class="div-table-responsive">'; // You can use div-table-responsive-no-min if you don't need reserved height for your table
print '<table class="tagtable nobottomiftotal noborder liste'.($moreforfilter ? " listwithfilterbefore" : "").'">'."\n";

// Fields title search
// --------------------------------------------------------------------
print '<tr class="liste_titre_filter">';
// Action column
if ($conf->main_checkbox_left_column) {
	print '<td class="liste_titre center maxwidthsearch">';
	$searchpicto = $form->showFilterButtons('left');
	print $searchpicto;
	print '</td>';
}
foreach ($arrayfields as $key => $val) {
	$cssforfield = (empty($val['csslist']) ? (empty($val['css']) ? '' : $val['css']) : $val['csslist']);
	if ($key == 'status') {
		$cssforfield .= ($cssforfield ? ' ' : '').'center';
	} elseif (in_array($val['type'], array('date', 'datetime', 'timestamp'))) {
		$cssforfield .= ($cssforfield ? ' ' : '').'center';
	} elseif (in_array($val['type'], array('timestamp'))) {
		$cssforfield .= ($cssforfield ? ' ' : '').'nowrap';
	} elseif (in_array($val['type'], array('double(24,8)', 'double(6,3)', 'integer', 'real', 'price')) && !in_array($key, array('id', 'rowid', 'ref', 'status')) && $val['label'] != 'TechnicalID' && empty($val['arrayofkeyval'])) {
		$cssforfield .= ($cssforfield ? ' ' : '').'right';
	}
	if (!empty($arrayfields[$key]['checked'])) {

		print '<td class="liste_titre'.($cssforfield ? ' '.$cssforfield : '').($key == 'status' ? ' parentonrightofpage' : '').'">';

		if (!empty($val['arrayofkeyval']) && is_array($val['arrayofkeyval'])) {

			if (empty($val['searchmulti'])) {
				print $form->selectarray('search_'.$key, $val['arrayofkeyval'], (isset($search[$key]) ? $search[$key] : ''), 1, 0, 0, '', 1, 0, 0, '', 'maxwidth100'.($key == 'status' ? ' search_status11111 width100 onrightofpage' : ''), 1);
			} else {

				print $form->multiselectarray('search_'.$key, $val['arrayofkeyval'], (isset($search[$key]) ? $search[$key] : ''), 0, 0, 'maxwidth100'.($key == 'status' ? ' search_status22222 width100 onrightofpage' : ''), 1);
			}
		} elseif ((strpos($val['type'], 'integer:') === 0) || (strpos($val['type'], 'sellist:') === 0)) {
			print $object->showInputField($val, $key, (isset($search[$key]) ? $search[$key] : ''), '', '', 'search_', $cssforfield.' maxwidth250', 1);
		} elseif (preg_match('/^(date|timestamp|datetime)/', $val['type'])) {
			if ($key !== 'datestart') {
				print '<div class="nowrap">';
				print $form->selectDate($search[$key.'_dtstart'] ? $search[$key.'_dtstart'] : '', "search_".$key."_dtstart", 0, 0, 1, '', 1, 0, 0, '', '', '', '', 1, '', $langs->trans('From'));
				print '</div>';
				print '<div class="nowrap">';
				print $form->selectDate($search[$key.'_dtend'] ? $search[$key.'_dtend'] : '', "search_".$key."_dtend", 0, 0, 1, '', 1, 0, 0, '', '', '', '', 1, '', $langs->trans('to'));
				print '</div>';
			}

		} elseif ($key == 'lang') {
			require_once DOL_DOCUMENT_ROOT.'/core/class/html.formadmin.class.php';
			$formadmin = new FormAdmin($db);
			print $formadmin->select_language((isset($search[$key]) ? $search[$key] : ''), 'search_lang', 0, array(), 1, 0, 0, 'minwidth100imp maxwidth125', 2);
		} else {
			//Skip for SEARCH discount_amount_rfa
			if ($key == 'discount_amount_rfa' || $key == 'datestart') {
				//print '<td class="liste_titre">&nbsp;</td>';
			}else{
				print '<input type="text" class="flat maxwidth'.(in_array($val['type'], array('integer', 'price')) ? '50' : '75').'" name="search_'.$key.'" value="'.dol_escape_htmltag(isset($search[$key]) ? $search[$key] : '').'">';
			}
		}
		print '</td>';
	}
}

// Extra fields
include DOL_DOCUMENT_ROOT.'/core/tpl/extrafields_list_search_input.tpl.php';

// Fields from hook
$parameters = array('arrayfields' => $arrayfields);
$reshook = $hookmanager->executeHooks('printFieldListOption', $parameters, $object, $action); // Note that $action and $object may have been modified by hook
print $hookmanager->resPrint;

// Action column
if (!$conf->main_checkbox_left_column) {
	print '<td class="liste_titre center maxwidthsearch">';
	$searchpicto = $form->showFilterButtons();
	print $searchpicto;
	print '</td>';
}
print '</tr>'."\n";

$totalarray = array();
$totalarray['nbfield'] = 0;

// Fields title label
// --------------------------------------------------------------------
print '<tr class="liste_titre">';
// Action column
if ($conf->main_checkbox_left_column) {
	print getTitleFieldOfList($selectedfields, 0, $_SERVER["PHP_SELF"], '', '', '', '', $sortfield, $sortorder, 'center maxwidthsearch ')."\n";
	$totalarray['nbfield']++;
}
foreach ($arrayfields as $key => $val) {
	$cssforfield = (empty($val['csslist']) ? (empty($val['css']) ? '' : $val['css']) : $val['csslist']);
	if ($key == 'status') {
		$cssforfield .= ($cssforfield ? ' ' : '').'center';
	} elseif (in_array($val['type'], array('date', 'datetime', 'timestamp'))) {
		$cssforfield .= ($cssforfield ? ' ' : '').'center';
	} elseif (in_array($val['type'], array('timestamp'))) {
		$cssforfield .= ($cssforfield ? ' ' : '').'nowrap';
	} elseif (in_array($val['type'], array('double(24,8)', 'double(6,3)', 'integer', 'real', 'price')) && !in_array($key, array('id', 'rowid', 'ref', 'status')) && $val['label'] != 'TechnicalID' && empty($val['arrayofkeyval'])) {
		$cssforfield .= ($cssforfield ? ' ' : '').'right';
	}
	$cssforfield = preg_replace('/small\s*/', '', $cssforfield);	// the 'small' css must not be used for the title label
	if (!empty($arrayfields[$key]['checked'])) {

		if ($key == 'discount_amount_rfa'){
			print getTitleFieldOfList($arrayfields[$key]['label'], 0, $_SERVER['PHP_SELF'], '', '', $param, ($cssforfield ? 'class="'.$cssforfield.'"' : ''), $sortfield, $sortorder, ($cssforfield ? $cssforfield.' ' : ''), 0, (empty($val['helplist']) ? '' : $val['helplist']))."\n";

		}else{
			print getTitleFieldOfList($arrayfields[$key]['label'], 0, $_SERVER['PHP_SELF'], $key, '', $param, ($cssforfield ? 'class="'.$cssforfield.'"' : ''), $sortfield, $sortorder, ($cssforfield ? $cssforfield.' ' : ''), 0, (empty($val['helplist']) ? '' : $val['helplist']))."\n";

		}
		$totalarray['nbfield']++;
	}
}
// Extra fields
include DOL_DOCUMENT_ROOT.'/core/tpl/extrafields_list_search_title.tpl.php';
// Hook fields
$parameters = array('arrayfields' => $arrayfields, 'param' => $param, 'sortfield' => $sortfield, 'sortorder' => $sortorder, 'totalarray' => &$totalarray);
$reshook = $hookmanager->executeHooks('printFieldListTitle', $parameters, $object, $action); // Note that $action and $object may have been modified by hook
print $hookmanager->resPrint;
// Action column
if (!$conf->main_checkbox_left_column) {
	print getTitleFieldOfList($selectedfields, 0, $_SERVER["PHP_SELF"], '', '', '', '', $sortfield, $sortorder, 'center maxwidthsearch ')."\n";
	$totalarray['nbfield']++;
}
print '</tr>'."\n";

// Detect if we need a fetch on each output line
$needToFetchEachLine = 0;
if (isset($extrafields->attributes[$object->table_element]['computed']) && is_array($extrafields->attributes[$object->table_element]['computed']) && count($extrafields->attributes[$object->table_element]['computed']) > 0) {
	foreach ($extrafields->attributes[$object->table_element]['computed'] as $key => $val) {
		if (!is_null($val) && preg_match('/\$object/', $val)) {
			$needToFetchEachLine++; // There is at least one compute field that use $object
		}
	}
}


// Loop on record
// --------------------------------------------------------------------
$i = 0;
$savnbfield = $totalarray['nbfield'];
$totalarray = array();
$totalarray['nbfield'] = 0;
$imaxinloop = ($limit ? min($num, $limit) : $num);
while ($i < $imaxinloop) {
	$obj = $db->fetch_object($resql);
	if (empty($obj)) {
		break; // Should not happen
	}

	// Show line of result
	$j = 0;
	print '<tr data-rowid="' . $object->id . '" class="oddeven">';

	// Action column
	if ($conf->main_checkbox_left_column) {
		print '<td class="nowrap center">';

		print '</td>';
		if (!$i) {
			$totalarray['nbfield']++;
		}


		foreach ($arrayfields as $key => $val) {
			$cssforfield = (empty($val['csslist']) ? (empty($val['css']) ? '' : $val['css']) : $val['csslist']);
			if (in_array($val['type'], array('date', 'datetime', 'timestamp'))) {
				$cssforfield .= ($cssforfield ? ' ' : '') . 'center';
			} elseif ($key == 'status') {
				$cssforfield .= ($cssforfield ? ' ' : '') . 'center';
			}

			if (in_array($val['type'], array('timestamp'))) {
				$cssforfield .= ($cssforfield ? ' ' : '') . 'nowraponall';
			} elseif ($key == 'ref') {
				$cssforfield .= ($cssforfield ? ' ' : '') . 'nowraponall';
			}

			if (in_array($val['type'], array('double(24,8)', 'double(6,3)', 'integer', 'real', 'price')) && !in_array($key, array('id', 'rowid', 'ref', 'status')) && empty($val['arrayofkeyval'])) {
				$cssforfield .= ($cssforfield ? ' ' : '') . 'right';
			}

			if (!empty($arrayfields[$key]['checked'])) {
				print '<td' . ($cssforfield ? ' class="' . $cssforfield . ((preg_match('/tdoverflow/', $cssforfield) && !in_array($val['type'], array('ip', 'url')) && !is_numeric($object->$key)) ? ' classfortooltip' : '') . '"' : '');
				if (preg_match('/tdoverflow/', $cssforfield) && !in_array($val['type'], array('ip', 'url')) && !is_numeric($object->$key) && !in_array($key, array('ref'))) {
					print ' title="' . dol_escape_htmltag($object->$key) . '"';
				}
				print '>';
				if ($key == 'status') {
					$object->status = $obj->status;
					print $object->getLibStatut(5);
				} elseif ($key == 'rowid') {
					print $object->showOutputField($val, $key, $object->id, '');
				} elseif ($key == 'ca_achats') {
					$year = (int)(GETPOST('search_year', 'int') ? GETPOST('search_year', 'int') : (isset($obj->datestart) ? substr($obj->datestart, 0, 4) : date('Y')));

					$url = DOL_URL_ROOT . '/fourn/facture/list.php'
						. '?socid=' . (int)$obj->fk_soc
						. '&search_date_startday=1'
						. '&search_date_startmonth=1'
						. '&search_date_startyear=' . $search_year
						. '&search_date_endday=31'
						. '&search_date_endmonth=12'
						. '&search_date_endyear=' . $search_year
						. '&search_status=' . FactureFournisseur::STATUS_CLOSED;

					print '<a href="' . dol_escape_htmltag($url) . '">' . price($obj->ca_achats) . '</a>';

				} elseif ($key == 'datestart') {
					$object->datestart = $obj->datestart;
					$dateStartYear = substr($object->datestart, 0, 4);   // "2025"
					print $object->datestart;
				} else {
					print $object->showOutputField($val, $key, $obj->$key, '');
				}
				print '</td>';
				if (!$i) {
					$totalarray['nbfield']++;
				}
				if (!empty($val['isameasure']) && $val['isameasure'] == 1) {
					if (!$i) {
						$totalarray['pos'][$totalarray['nbfield']] = $key;
					}
					if (!isset($totalarray['val'])) {
						$totalarray['val'] = array();
					}
					if (!isset($totalarray['val'][$key])) {
						$totalarray['val'][$key] = 0;
					}
					$totalarray['val'][$key] += $object->$key;
				}
				//CALCULATE discount_amount_rfa
				if (!empty($obj->ca_achats) && !empty($obj->taux_rfa)) {
					$obj->discount_amount_rfa = $obj->ca_achats / 100 * $obj->taux_rfa;
				}
			}
		}
		//exit;
		// Extra fields
		include DOL_DOCUMENT_ROOT . '/core/tpl/extrafields_list_print_fields.tpl.php';
		// Fields from hook
		$parameters = array('arrayfields' => $arrayfields, 'object' => $object, 'obj' => $obj, 'i' => $i, 'totalarray' => &$totalarray);
		$reshook = $hookmanager->executeHooks('printFieldListValue', $parameters, $object, $action); // Note that $action and $object may have been modified by hook
		print $hookmanager->resPrint;

		// Action column
		if (empty($conf->main_checkbox_left_column)) {
			print '<td class="nowrap center">';

			print '</td>';
			if (!$i) {
				$totalarray['nbfield']++;
			}
		}

		print '</tr>' . "\n";
	}

	$i++;
}

// Show total line
include DOL_DOCUMENT_ROOT.'/core/tpl/list_print_total.tpl.php';

// If no record found
if ($num == 0) {
	$colspan = 1;
	foreach ($arrayfields as $key => $val) {
		if (!empty($val['checked'])) {
			$colspan++;
		}
	}
	print '<tr><td colspan="'.$colspan.'"><span class="opacitymedium">'.$langs->trans("NoRecordFound").'</span></td></tr>';
}


$db->free($resql);

$parameters = array('arrayfields' => $arrayfields, 'sql' => $sql);
$reshook = $hookmanager->executeHooks('printFieldListFooter', $parameters, $object, $action); // Note that $action and $object may have been modified by hook
print $hookmanager->resPrint;

print '</table>'."\n";
print '</div>'."\n";

print '</form>'."\n";


// End of page
llxFooter();
$db->close();
