<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:stns1="urn:Services.customerStockAndPriceService.Classes" xmlns:tns="urn:PreProdSecureStockAndPriceCheck" xmlns:xs="http://www.w3.org/2001/XMLSchema" name="PreProdSecureStockAndPriceCheck" targetNamespace="urn:PreProdSecureStockAndPriceCheck">
<!-- ====================================================================== -->
<!--Types-->
<!-- ====================================================================== -->
   <wsdl:types>
      <xs:schema targetNamespace="urn:Services.customerStockAndPriceService.Classes">
         <xs:import namespace="http://schemas.xmlsoap.org/soap/encoding/" schemaLocation="http://schemas.xmlsoap.org/soap/encoding/"/>
         <xs:complexType name="InputDetailRow">
            <xs:all>
               <xs:element name="lineNr" type="xs:int"/>
               <xs:element name="productID" type="xs:string"/>
               <xs:element name="orderUnit" type="xs:string"/>
               <xs:element name="quantity" type="xs:float"/>
               <xs:element name="deliveryDate" type="xs:dateTime"/>
            </xs:all>
         </xs:complexType>
         <xs:complexType name="InputDetailRowArray">
            <xs:complexContent>
               <xs:restriction base="soapenc:Array">
                  <xs:attribute ref="soapenc:arrayType" wsdl:arrayType="stns1:InputDetailRow[]"/>
               </xs:restriction>
            </xs:complexContent>
         </xs:complexType>
         <xs:complexType name="InputParameters">
            <xs:all>
               <xs:element name="enquiryType" type="xs:string"/>
               <xs:element name="userCode" type="xs:string"/>
               <xs:element name="customerID" type="xs:string"/>
               <xs:element name="AntalisDeliveryAddressID" type="xs:string"/>
               <xs:element name="orderType" type="xs:string"/>
               <xs:element name="detailRow" type="stns1:InputDetailRowArray"/>
            </xs:all>
         </xs:complexType>
         <xs:complexType name="OutputAdditionalPricing">
            <xs:all>
               <xs:element name="lineNr" type="xs:int"/>
               <xs:element name="priceCode" type="xs:string"/>
               <xs:element name="rate" type="xs:float"/>
               <xs:element name="rateCurrency" type="xs:string"/>
               <xs:element name="priceQty" type="xs:int"/>
               <xs:element name="priceUnit" type="xs:string"/>
               <xs:element name="totalPrice" type="xs:float"/>
            </xs:all>
         </xs:complexType>
         <xs:complexType name="OutputAdditionalPricingArray">
            <xs:complexContent>
               <xs:restriction base="soapenc:Array">
                  <xs:attribute ref="soapenc:arrayType" wsdl:arrayType="stns1:OutputAdditionalPricing[]"/>
               </xs:restriction>
            </xs:complexContent>
         </xs:complexType>
         <xs:complexType name="OutputAvailabilityLine">
            <xs:all>
               <xs:element name="lineNr" type="xs:int"/>
               <xs:element name="availableQty" type="xs:float"/>
               <xs:element name="availableDate" type="xs:dateTime"/>
            </xs:all>
         </xs:complexType>
         <xs:complexType name="OutputAvailabilityLineArray">
            <xs:complexContent>
               <xs:restriction base="soapenc:Array">
                  <xs:attribute ref="soapenc:arrayType" wsdl:arrayType="stns1:OutputAvailabilityLine[]"/>
               </xs:restriction>
            </xs:complexContent>
         </xs:complexType>
         <xs:complexType name="OutputDetailRow">
            <xs:all>
               <xs:element name="lineNr" type="xs:int"/>
               <xs:element name="productID" type="xs:string"/>
               <xs:element name="orderUnit" type="xs:string"/>
               <xs:element name="quantity" type="xs:float"/>
               <xs:element name="unitPrice" type="xs:float"/>
               <xs:element name="priceQty" type="xs:float"/>
               <xs:element name="priceUnit" type="xs:string"/>
               <xs:element name="materialPrice" type="xs:float"/>
               <xs:element name="VAT" type="xs:float"/>
               <xs:element name="totalPrice" type="xs:float"/>
               <xs:element name="discount" type="xs:float"/>
               <xs:element name="available" type="xs:string"/>
               <xs:element name="priceValidTill" type="xs:dateTime"/>
               <xs:element name="errorID" type="xs:string"/>
               <xs:element name="availabilityLine" type="stns1:OutputAvailabilityLineArray"/>
               <xs:element name="additionalPricing" type="stns1:OutputAdditionalPricingArray"/>
            </xs:all>
         </xs:complexType>
         <xs:complexType name="OutputDetailRowArray">
            <xs:complexContent>
               <xs:restriction base="soapenc:Array">
                  <xs:attribute ref="soapenc:arrayType" wsdl:arrayType="stns1:OutputDetailRow[]"/>
               </xs:restriction>
            </xs:complexContent>
         </xs:complexType>
         <xs:complexType name="OutputParameters">
            <xs:all>
               <xs:element name="enquiryType" type="xs:string"/>
               <xs:element name="customerID" type="xs:string"/>
               <xs:element name="AntalisDeliveryAddressID" type="xs:string"/>
               <xs:element name="orderType" type="xs:string"/>
               <xs:element name="currency" type="xs:string"/>
               <xs:element name="errorID" type="xs:string"/>
               <xs:element name="detailRow" type="stns1:OutputDetailRowArray"/>
               <xs:element name="additionalPricing" type="stns1:OutputAdditionalPricingArray"/>
            </xs:all>
         </xs:complexType>
      </xs:schema>
   </wsdl:types>
<!-- ====================================================================== -->
<!--Message-->
<!-- ====================================================================== -->
   <wsdl:message name="customerStockAndPricePortType_stockPriceCheck__Request">
      <wsdl:part name="stockPriceInput" type="stns1:InputParameters"/>
   </wsdl:message>
   <wsdl:message name="customerStockAndPricePortType_stockPriceCheck__Response">
      <wsdl:part name="stockPriceOutput" type="stns1:OutputParameters"/>
   </wsdl:message>
<!-- ====================================================================== -->
<!--Port Type-->
<!-- ====================================================================== -->
   <wsdl:portType name="customerStockAndPricePortType_PortType">
      <wsdl:documentation>Returns stock and price info.</wsdl:documentation>
      <wsdl:operation name="stockPriceCheck">
         <wsdl:documentation>Returns stock and price info.</wsdl:documentation>
         <wsdl:input message="tns:customerStockAndPricePortType_stockPriceCheck__Request"/>
         <wsdl:output message="tns:customerStockAndPricePortType_stockPriceCheck__Response"/>
      </wsdl:operation>
   </wsdl:portType>
<!-- ====================================================================== -->
<!--Binding-->
<!-- ====================================================================== -->
   <wsdl:binding name="customerStockAndPricePortType_SOAPBinding" type="tns:customerStockAndPricePortType_PortType">
      <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
      <wsdl:operation name="stockPriceCheck">
         <soap:operation soapAction=""/>
         <wsdl:input>
            <soap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="urn:Services.customerStockAndPriceService.customerStockAndPricePortType.customerStockAndPricePortType" use="encoded"/>
         </wsdl:input>
         <wsdl:output>
            <soap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="urn:Services.customerStockAndPriceService.customerStockAndPricePortType.customerStockAndPricePortType" use="encoded"/>
         </wsdl:output>
      </wsdl:operation>
   </wsdl:binding>
<!-- ====================================================================== -->
<!--Service -->
<!-- ====================================================================== -->
   <wsdl:service name="SOAPService">
      <wsdl:port binding="tns:customerStockAndPricePortType_SOAPBinding" name="customerStockAndPricePortType">
         <soap:address location="https://etrade.antalis-commerce.com:1000/localhost/PreProdSecureStockAndPriceCheck/SOAPServiceInstance/Services/customerStockAndPriceService/customerStockAndPricePortType/customerStockAndPricePortType"/>
      </wsdl:port>
   </wsdl:service>
</wsdl:definitions>
